### ISSUE TITLE
tokenservices stability 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/vdc#49]
https://github.com/threefoldfoundation/tft-stellar/issues/241

**Comment by robvanmieghem** [comment]
Is solved

**Comment by RafyAmgadBenjamin** [comment]
- we still facing this issue.
- we are kind of blocking on creating `VDC` as `stellar` is down

https://github.com/threefoldtech/vdc/issues/33

**Comment by robvanmieghem** [comment]
stellar testnet is down ( overloaded), not stellar as a whole

**Comment by RafyAmgadBenjamin** [comment]
> stellar testnet is down ( overloaded), not stellar as a whole

Actually, it happened with us on `devnet`, sometimes it works and sometimes it doesn't

**Comment by ashraffouda** [comment]
also happened with me manytimes yesterday and today with devnet

**Comment by robvanmieghem** [comment]
@ashraffouda can I have the complete stacktrace?

**Comment by ashraffouda** [comment]
I don't have the full stacktrace. but this what I was doing 
```
vdc = j.sals.vdc.new(vdc_name="ashroof1000", owner_tname="ashraf.3bot", flavor="Gold")
deployer = vdc_inst.get_deployer("11111111")
````
and I can not reproduce it atm

**Comment by robvanmieghem** [comment]
@ashraffouda Can you look in the wallets page in the 3bot and check on which network it is?

**Comment by ashraffouda** [comment]
it is "TEST"
